--Total Revenue
SELECT SUM(TOTAL_SALE) AS TOTAL_REVENUE
FROM ORDER_DETAILS;

--Total Customers
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMERS;

--Total Products
SELECT COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS;

--Total Orders
SELECT COUNT(*) AS TOTAL_ORDERS
FROM ORDERS;

--Total Distinct orders
SELECT COUNT(*) AS TOTAL_ORDER_DETAILS
FROM ORDER_DETAILS;
