--Create table Sales_data(Staging table)
  CREATE TABLE "SALES_DATA"
   (
    "ORDER_ID" VARCHAR2(50),
	"PURCHASE_DATE" DATE,
	"PURCHASE_MONTH" NUMBER,
	"CUSTOMER_ID" VARCHAR2(50),
	"CUSTOMER_NAME" VARCHAR2(100),
	"CUSTOMER_AGE" NUMBER,
	"CUSTOMER_SEGMENT" VARCHAR2(50),
	"COUNTRY" VARCHAR2(50),
	"REGION" VARCHAR2(50),
	"CITY" VARCHAR2(50),
	"POSTAL_CODE" VARCHAR2(20),
	"PRODUCT_CATEGORY" VARCHAR2(50),
	"SUB_CATEGORY" VARCHAR2(50),
	"PRODUCT" VARCHAR2(50),
	"UNIT_PRICE" NUMBER(10,2),
	"QUANTITY" NUMBER,
	"TOTAL_SALE" NUMBER(12,2)
   ) ;
--Normalized
--Create table CUSTOMERS
  CREATE TABLE "CUSTOMERS"
   (
    "CUSTOMER_ID" VARCHAR2(50),
	"CUSTOMER_NAME" VARCHAR2(100),
	"CUSTOMER_AGE" NUMBER,
	"CUSTOMER_SEGMENT" VARCHAR2(50),
	"COUNTRY" VARCHAR2(50),
	"REGION" VARCHAR2(50),
	"CITY" VARCHAR2(50),
	"POSTAL_CODE" VARCHAR2(20),
	 PRIMARY KEY ("CUSTOMER_ID")
   ) ;

--Create table PRODUCTS
    CREATE TABLE "PRODUCTS"
   (
    "PRODUCT_ID" NUMBER,
	"PRODUCT_NAME" VARCHAR2(50),
	"PRODUCT_CATEGORY" VARCHAR2(50),
	"SUB_CATEGORY" VARCHAR2(50),
	"UNIT_PRICE" NUMBER(10,2),
	 PRIMARY KEY ("PRODUCT_ID")
   ) ;

--Create table ORDERS
  CREATE TABLE "ORDERS"
   (
    "ORDER_ID" VARCHAR2(50),
	"PURCHASE_DATE" DATE,
	"PURCHASE_MONTH" NUMBER,
	"CUSTOMER_ID" VARCHAR2(50) NOT NULL ENABLE,
	 PRIMARY KEY ("ORDER_ID")
     CONSTRAINT "FK" FOREIGN KEY ("CUSTOMER_ID")
     REFERENCES "CUSTOMERS" ("CUSTOMER_ID") ENABLE;
   ) ;



--Create table ORDER DETAILS
  CREATE TABLE "ORDER_DETAILS"
   (
    "ORDER_DETAILS_ID" NUMBER,
	"ORDER_ID" VARCHAR2(50),
	"PRODUCT_ID" NUMBER,
	"QUANTITY" NUMBER,
	"TOTAL_SALE" NUMBER(12,2),
	 PRIMARY KEY ("ORDER_DETAILS_ID")
     CONSTRAINT "FK_ORDER_ITEMS_ORDER" FOREIGN KEY ("ORDER_ID")
	 REFERENCES "ORDERS" ("ORDER_ID") ENABLE;
     CONSTRAINT "FK_ORDER_ITEMS_PRODUCT" FOREIGN KEY ("PRODUCT_ID")
	 REFERENCES "PRODUCTS" ("PRODUCT_ID") ENABLE;
   ) ;
