--NORMALIZED QUERIES

--Revenue by Products
SELECT
    P.PRODUCT_NAME,
    SUM(OI.TOTAL_SALE) AS REVENUE
FROM ORDER_DETAILS OI
JOIN PRODUCTS P
    ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY REVENUE DESC;

--Revenue by Region
SELECT_
    C.REGION,
    SUM(OI.TOTAL_SALE) AS REVENUE
FROM ORDER_DETAILS OI
JOIN ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.REGION
ORDER BY REVENUE DESC;

--Revenue by Customer Segment
SELECT
    C.CUSTOMER_SEGMENT,
    SUM(OI.TOTAL_SALE) AS REVENUE
FROM ORDER_DETAILS OI
JOIN ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_SEGMENT
ORDER BY REVENUE DESC;

--Top 5 Customers
SELECT
    C.CUSTOMER_NAME,
    SUM(OI.TOTAL_SALE) AS REVENUE
FROM ORDER_DETAILS OI
JOIN ORDERS O
    ON OI.ORDER_ID = O.ORDER_ID
JOIN CUSTOMERS C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY REVENUE DESC
FETCH FIRST 5 ROWS ONLY;
